version: '3.7'

services: 
  salt_master:
    container_name: salt_master
    build:
      context: ./build
      args:
        - SALT_TYPE=MASTER
      dockerfile: Dockerfile.master
    environment:
      - SALT_TYPE=MASTER
    # ports:
    #   - "4505:4505"
    #   - "4506:4506"
  salt_syndic1:
    container_name: salt_syndic1
    build:
      context: ./build
      dockerfile: Dockerfile.master
      args:
        - SALT_TYPE=SYNDIC
        - SALT_MASTER=salt_master
    environment:
      - SALT_TYPE=SYNDIC
      - SALT_HOSTNAME=salt_syndic1
    # ports:
    #   - "4505:4505"
    #   - "4506:4506"
  salt_syndic2:
    container_name: salt_syndic2
    build:
      context: ./build
      dockerfile: Dockerfile.master
      args:
        - SALT_TYPE=SYNDIC
        - SALT_MASTER=salt_master
    environment:
      - SALT_TYPE=SYNDIC
      - SALT_HOSTNAME=salt_syndic2
    # ports:
    #   - "4505:4505"
    #   - "4506:4506"
  salt_minion:
    build:
      context: ./build
      dockerfile: Dockerfile.minion
      args:
        - SALT_TYPE=MINION
        - SALT_MASTER=salt_master
    environment:
      - SALT_TYPE=MINION
    depends_on:
      - salt_master

  salt_api:
    container_name: salt_api
    image: opensuse/salt-api
    ports:
      - "6000:8000"
    # volumes:
    #   - ./salt:/etc/salt
    depends_on:
      - salt_master

  saltpad:
    container_name: saltpad
    image: bbinet/saltpad
    ports:
      - "8080:80"
    environment:
      - SALTAPI_URL=http://salt-api:8000
      - SALTAPI_USER=saltpad
      - SALTAPI_PASS=saltpad
    depends_on:
      - salt_api

networks:
  default:
    name: salt-network